-define (ADMINISTRATION,                        14).    % 行政
-define (PROGRAM,                               15).    % 程序
-define (ADMIN,                                999).    % 行政
-define (TEST,                                  50).    % 程序
