{
    [
        '../src/*',
        '../src/api/*',
        '../src/gen/*',
        '../src/gen/api_out/*',
        '../src/gen/code_db/*',
        '../src/lib/*',
        '../src/mod/*',
        '../src/process/*',
        '../src/process/test/*',
        '../src/process/four_color/*',
        '../src/system/*',
        '../src/release_check/*'
    ],
    [
        debug_info,
        {d, debug},
        {outdir, "./"},
        {i, "../include"}
    ]
}.



